# =============================================================
# Project
# =============================================================
sonar.projectKey=logbeacon-backend
sonar.projectName=LogBeacon Backend
sonar.projectVersion=1.0


# =============================================================
# Source
# =============================================================
sonar.sources=app,wsgi.py

# Encoding
sonar.sourceEncoding=UTF-8


# =============================================================
# Python
# =============================================================
sonar.python.version=3.11


# =============================================================
# Tests
# =============================================================
sonar.tests=tests

sonar.test.inclusions=**/test_*.py,**/*_test.py


# =============================================================
# Coverage
# =============================================================
sonar.python.coverage.reportPaths=coverage.xml

# Do not calculate coverage for test files
sonar.coverage.exclusions=tests/**,**/test_*.py,**/*_test.py


# =============================================================
# Exclusions
# =============================================================
sonar.exclusions=**/__pycache__/**,**/venv/**,**/.venv/**,migrations/**


# =============================================================
# SCM
# =============================================================
sonar.scm.provider=git